(function() {var m="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global?global:this,n={};function p(a,b){(n[a]=n[a]||[]).push(b);var c=m;a=a.split(".");for(var d=0;d<a.length-1&&c;d++)c=c[a[d]];a=a[a.length-1];c&&c[a]instanceof Function&&(c[a]=b(c[a]))}
function q(){q=function(){};if(!m.Symbol){m.Symbol=t;var a=[],b=function(b){return function(d){a=[];d=b(d);for(var k=[],g=0,l=d.length;g<l;g++){var h;a:if(h=d[g],14>h.length)h=!1;else{for(var f=0;14>f;f++)if(h[f]!="jscomp_symbol_"[f]){h=!1;break a}h=!0}h?a.push(d[g]):k.push(d[g])}return k}};p("Object.keys",b);p("Object.getOwnPropertyNames",b);p("Object.getOwnPropertySymbols",function(c){return function(d){b.W=Object.getOwnPropertyNames(d);a.push.apply(c(d));return a}})}}var u=0;
function t(a){return"jscomp_symbol_"+a+u++}function v(){q();m.Symbol.iterator||(m.Symbol.iterator=m.Symbol("iterator"));v=function(){}}function w(a,b){v();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var k=c++;return{value:b(k,a[k]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d}
for(var x="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},y=m,z=["Array","prototype","keys"],A=0;A<z.length-1;A++){var B=z[A];B in y||(y[B]={});y=y[B]}var C=z[z.length-1],D=y[C],E=D?D:function(){return w(this,function(a){return a})};
if(E!=D){for(var F=n["Array.prototype.keys"]||[],A=0;A<F.length;A++)E=F[A](E);x(y,C,{configurable:!0,writable:!0,value:E})}function H(a,b){this.v=a;this.namespace=void 0===b?null:b}H.prototype.setItem=function(a,b){try{return this.v.setItem(null==this.namespace?a:this.namespace+"."+a,b),!0}catch(c){return!1}};H.prototype.getItem=function(a){return this.v.getItem(null==this.namespace?a:this.namespace+"."+a)};
H.prototype.removeItem=function(a){this.v.removeItem(null==this.namespace?a:this.namespace+"."+a)};function I(){this.xhr=null}I.prototype.cancel=function(){this.xhr&&(this.xhr.abort(),this.xhr=null)};I.prototype.finish=function(){this.xhr=null};function J(a){this.C=a&&a.analyticsContext||null;this.o=a&&a.authToken||null;this.u=a&&a.authzToken||null;this.D=a&&a.brandRestriction||null;this.F=a&&a.buildName||null;this.G=a&&a.buildSha||null;this.i=a&&a.csrfTokens||{};this.w=a&&a.serverRoot||null;this.O=!!this.w;this.R=this.w?this.w+"/_ajax":"/_ajax"}
function K(a){var b=a.indexOf("/",1);return-1==b?a:a.substring(0,b)}J.prototype.get=function(a,b){var c=new I;this.send("GET",a,null,!0,null,c,b);return c};J.prototype.post=function(a,b,c){var d=new I;L(this,"POST",a,b,!0,0,d,c);return d};
function L(a,b,c,d,k,g,l,h){var f=K(c);if(f in a.i){var e=a.i[f];a.send(b,c,d,k,e,l,function(r,G){418==r&&1>g?(a.i[f]==e&&delete a.i[f],L(a,b,c,d,k,g+1,l,h)):(h&&h(r,G),l.finish())})}else a.send("GET","/csrf"+f,null,k,null,l,function(e,G){200==e?(f in a.i||(a.i[f]=String(G)),L(a,b,c,d,k,g,l,h)):(h(e,null),l.finish())})}
J.prototype.send=function(a,b,c,d,k,g,l){function h(){4==e.readyState&&f()}function f(){var a,b,c;try{a=e.status;var d,h;try{d=e.getResponseHeader("X-Canva-Auth")}catch(f){}try{h=e.getResponseHeader("X-Canva-Authz")}catch(f){}d&&(r.o="!"!=d?d:null);h&&(r.u="!"!=h?h:null);b=e.responseText}catch(f){if(f.message&&f.message.match(/c00c023f/))a=0,b="";else throw g.finish(),f;}b=b&&b.trim?b.trim():"";d=b.substring(0,20);if(0<d.length){if("'\"])}while(1);\x3c/x\x3e//"!=d){l(500,null);g.finish();return}b=
b.substring(20);try{c=JSON.parse(b)}catch(f){l(500,null);g.finish();return}}else c=null;l(a,c);g.finish()}b=this.R+b;var e=g.xhr=new XMLHttpRequest,r=this;e.open(a,b,d);this.O&&(e.withCredentials=!0);"GET"!=a&&k&&e.setRequestHeader("X-Csrf-Token",k);this.C&&e.setRequestHeader("X-Canva-Analytics",this.C);this.o&&e.setRequestHeader("X-Canva-Auth",this.o);this.u&&e.setRequestHeader("X-Canva-Authz",this.u);this.D&&e.setRequestHeader("X-Canva-Brand",this.D);this.F&&e.setRequestHeader("X-Canva-Build-Name",
this.F);this.G&&e.setRequestHeader("X-Canva-Build-Sha",this.G);null===c||void 0===c?a=null:(e.setRequestHeader("Content-Type","application/json;charset\x3dUTF-8"),a=JSON.stringify(c));d?(e.onreadystatechange=h,e.send(a)):(e.send(a),f())};function M(){this.view=null}M.prototype.j=function(a){var b=this;this.view&&(this.view.remove(),this.view=null);a&&(this.view=new N,this.view.render(a).$el.appendTo("body"),this.view.once("hide",function(){return b.trigger("hide")}))};M.prototype.on=Backbone.Events.on;M.prototype.off=Backbone.Events.off;M.prototype.trigger=Backbone.Events.trigger;function N(){}N=Backbone.View.extend({className:"systemAlert"});N.prototype.events=function(){return{"click .systemAlertHide":this.hide}};
N.prototype.hide=function(a){a.preventDefault();this.trigger("hide")};N.prototype.render=function(a){var b=this.el;soy.asserts.assertType(goog.isString(a)||a instanceof goog.soy.data.SanitizedContent,"message",a,"string|goog.soy.data.SanitizedContent");a=soydata.VERY_UNSAFE.ordainSanitizedHtml('\x3cp class\x3d"systemAlertMessage"\x3e'+soy.$$escapeHtml(a)+'\x3c/p\x3e\x3ca class\x3d"systemAlertHide" href\x3d"#"\x3eOK, hide\x3c/a\x3e');b.innerHTML=a;return this};function O(){}O.prototype.now=function(){return Date.now()};var Q=new O;var S=new R;function R(){}R.prototype.setInterval=function(a,b){return window.setInterval(a,b)};R.prototype.clearInterval=function(a){window.clearInterval(a)};R.prototype.setTimeout=function(a,b){return window.setTimeout(a,b)};R.prototype.clearTimeout=function(a){window.clearTimeout(a)};R.prototype.requestAnimationFrame=function(a){return window.requestAnimationFrame(a)};R.prototype.cancelAnimationFrame=function(a){window.cancelAnimationFrame(a)};function T(a,b,c,d,k){var g=this;this.view=a;this.g=this.message=null;this.H=c;this.N=b;this.K=d;this.J=k;this.l=null;this.view.on("hide",function(){if(g.message){var a=g.H,b="acknowledged."+g.message,c=g.J.now();try{var d=JSON.stringify(c);a.setItem(b,d)}catch(k){}g.j(null)}})}function U(a){a.g&&a.g.cancel();a.g=a.N.get("/alerts/active",function(b,c){a.g=null;200===b&&a.j(c)})}
T.prototype.start=function(a){var b=this;null==this.l&&(this.j(void 0!==a?a:null),this.l=this.K.setInterval(function(){return U(b)},18E5))};T.prototype.stop=function(){null!=this.g&&(this.g.cancel(),this.g=null);null!=this.l&&this.K.clearInterval(this.l)};T.prototype.j=function(a){if(a){var b;try{var c=this.H.getItem("acknowledged."+a);b=null!==c?JSON.parse(c):null}catch(d){b=null}if(null!=b&&864E5>this.J.now()-b)return}this.message=a;this.view.j(a)};$(function(){var a;if(window.localStorage)a=new H(window.localStorage,"SystemAlertController");else throw Error("ClientStore: localStorage is not defined on window, likely an unsupported browser");(new T(new M,new J(window.httpServiceConfig),a,S,Q)).start(window.systemAlert)});})();
